### ISSUE TITLE
Envious uses env insertion order not _n_ values to determine order of a Vec 

### ISSUE THREAD

**Issue by arifd** [TheNeikos/envious#29]
Hi, first off, fantastic crate!!

```rs
use serde::Deserialize;

#[derive(Deserialize, Debug)]
struct Config {
    order: Vec<String>,
}

fn main() {
    std::env::set_var("order__1_", "second");
    std::env::set_var("order__0_", "first");
    let config: Config = envious::Config::default().build_from_env().expect("Could not deserialize from env");
    assert_eq!(config.order, vec!["first".to_string(), "second".to_string()]);
}
```

This will panic, because second was declared first, despite giving it a numeric value of 1.

Not sure how you feel, but I found this suprising UX.

Many thanks!

**Comment by TheNeikos** [comment]
Heya! 👋 Happy you like the crate.

> This will panic, because second was declared first, despite giving it a numeric value of 1.

Sadly that is one of the shortcomings currently. I remember it being a bit complicated in serde, because structs can also be encoded as arrays. And I did not have the time yet to fix it.

PRs welcome if anyone wants to take a shot at it!

**Comment by arifd** [comment]
Hmmm... I'm honestly not sure what the best thing to do is. :/

**Comment by TheNeikos** [comment]
Breaking changes are fine. Going from 0.2 -> 0.3 is not a 'simple' version bump. Cargo will not automatically update to it. 

I don't think that dependabot ignores semver here.

Since I do have to require that people know what semver is that is the best I can do here.
