### ISSUE TITLE
Deserialize HashMap

### ISSUE THREAD

**Issue by curiousmindflow** [TheNeikos/envious#31]
Hello,

I wanted to know if it's currently possible to deserialize a HashMap ?
And if not, is it part of your roadmap ?

Thank you !

**Comment by TheNeikos** [comment]
Heya!

I don't see why it shouldn't work. Did you try it out and encountered some issues?

**Comment by curiousmindflow** [comment]
I did try, but i wasn't able to see the struct updated.

I think i'm not naming the env var correctly and i didn't found example for HashMap specifically.
Can you give me an example please ?

For the type:

```Rust
struct Dummy {
   map0: HashMap::<String, String>,
   inner: DummyInner
}

struct DummyInner {
   map1: HashMap::<String, String>,
}
```

**Comment by TheNeikos** [comment]
I just added some tests for deserializing a hashmap: 

https://github.com/TheNeikos/envious/blob/b2cd39ddf26ebba94dbe7d959e70fe37f364d02b/tests/hashmap.rs#L6-L25

Hope that helps you!

**Comment by curiousmindflow** [comment]
Hello,

Okay, it's working !

Really fine and helpful crate !!
Thank you

**Comment by TheNeikos** [comment]
Awesome! :tada: 

Have fun!
